version: '3'
services:
  dev:
    build:
      context: .
      args:
        - USERNAME=yf
        - USER_UID=1024
    runtime: nvidia
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ipc: host
    volumes:
      - /home/yf/workspace:/home/yf/workspace
      - /home/yf/data:/home/yf/data
    ports:
      - 7860:7860
    command: /bin/sh -c "while sleep 1000; do :; done"